### ISSUE TITLE
How to get evolutionary steps?

### ISSUE THREAD

**Issue by wt12318** [danro9685/ASCETIC#10]
Hi,
In the `An introduction to the ASCETIC R package`, the last step is that extraction of evolutionary signatures significantly associated to prognosis. I want to know how to get the `evolutionary_steps` matrix from ASCETIC run steps including `asceticCCF`, `asceticCCFResampling` and `asceticCCFAssessment` . Could you provide more detailed procedure? Thank you.

**Comment by danro9685** [comment]
Dear @wt12318,
You need to obtain the evolutionary model either with asceticCCF or asceticCCFResampling. The first function run the basic ASCETIC pipeline, while asceticCCFResampling runs a robust estimation via resampling. asceticCCFAssessment instead computes the cross-validation score.
Once you have the evolutionaty model you can use the function evoSigs to obtain the signatures.
All the best,
Daniele

**Comment by wt12318** [comment]
Sorry, I did not get the point. The output of asceticCCF is:
```
> resExampleSingleSamples
$dataset
                  CTNNB1 TERT TP53
P-0044337-T01-IM6      0    1    1
P-0013464-T01-IM5      0    1    1
P-0017698-T02-IM6      1    0    0
P-0017415-T01-IM6      0    1    1
P-0017412-T01-IM6      0    1    0
P-0013060-T01-IM5      0    1    1
P-0001307-T01-IM3      1    1    0
P-0038810-T01-IM6      1    1    0
P-0036280-T01-IM6      0    1    1
P-0007157-T01-IM5      1    1    0

$ccfDataset
                     CTNNB1      TERT      TP53
P-0044337-T01-IM6 0.0000000 0.4932976 0.1640625
P-0013464-T01-IM5 0.0000000 0.2231760 0.2167256
P-0017698-T02-IM6 0.7376623 0.0000000 0.0000000
P-0017415-T01-IM6 0.0000000 0.2142857 0.2441506
P-0017412-T01-IM6 0.0000000 0.4850498 0.0000000
P-0013060-T01-IM5 0.0000000 0.2944785 0.3741935
P-0001307-T01-IM3 0.4627249 0.6725664 0.0000000
P-0038810-T01-IM6 0.5017422 0.8268956 0.0000000
P-0036280-T01-IM6 0.0000000 0.4246824 0.5553236
P-0007157-T01-IM5 0.9068323 0.0000000 0.0000000

$poset
  1 2 3
1 0 0 0
2 1 0 0
3 0 1 0

$inference
$inference$aic
  1 2 3
1 0 0 0
2 1 0 0
3 0 0 0
```
The output of  asceticCCFResampling is :
```

> resExampleSingleSamplesResampling
$dataset
                  CTNNB1 TERT TP53
P-0044337-T01-IM6      0    1    1
P-0013464-T01-IM5      0    1    1
P-0017698-T02-IM6      1    0    0
P-0017415-T01-IM6      0    1    1
P-0017412-T01-IM6      0    1    0
P-0013060-T01-IM5      0    1    1
P-0001307-T01-IM3      1    1    0
P-0038810-T01-IM6      1    1    0
P-0036280-T01-IM6      0    1    1
P-0007157-T01-IM5      1    1    0

$ccfDataset
                     CTNNB1      TERT      TP53
P-0044337-T01-IM6 0.0000000 0.4932976 0.1640625
P-0013464-T01-IM5 0.0000000 0.2231760 0.2167256
P-0017698-T02-IM6 0.7376623 0.0000000 0.0000000
P-0017415-T01-IM6 0.0000000 0.2142857 0.2441506
P-0017412-T01-IM6 0.0000000 0.4850498 0.0000000
P-0013060-T01-IM5 0.0000000 0.2944785 0.3741935
P-0001307-T01-IM3 0.4627249 0.6725664 0.0000000
P-0038810-T01-IM6 0.5017422 0.8268956 0.0000000
P-0036280-T01-IM6 0.0000000 0.4246824 0.5553236
P-0007157-T01-IM5 0.9068323 0.0000000 0.0000000

$rankingEstimate
       variable rank
CTNNB1        1    2
TERT          2    1
TP53          3    0

$poset
  1 2 3
1 0 0 0
2 1 0 0
3 0 1 0

$inference
$inference$aic
  1 2 3
1 0 0 0
2 1 0 0
3 0 0 0
```
However the evolutionary_steps needed by evoSigs is:
![图片](https://github.com/danro9685/ASCETIC/assets/39486023/6ba89e83-dbc2-451a-9e14-a1cd44024114)

How could I get this matrix from output of asceticCCF  or asceticCCFResampling?
Thank you.

**Comment by danro9685** [comment]
Oh I see, this is just a binary matrix where rows are the samples and the columns are the evo steps you can find as a results by the ASCETIC framework. You need to put 1 if a sample has the two mutations or 0 otherwise. You can also augment the matrix by adding single mutations besides cooccurrence of two. I can help with creating the matrix if you have troubles doing that.
Best,
Daniele
