### ISSUE TITLE
How CCF be calculated for gene level

### ISSUE THREAD

**Issue by wt12318** [danro9685/ASCETIC#11]
Hi,
Thanks for the tool. In the paper, each figure was shown as gene level evolutional signature. And the ccf was usually calculated in mutation level, how could it trans into gene level and use this tool (one gene might have multiple mutations and thus have many CCF values)?
Thanks

**Comment by danro9685** [comment]
Dear @wt12318,
Thank you for the interest in our framework.
In the paper if I get had multiple mutations, we considered for each patient the one at higher CCF (occurring earlier).
All the best,
Daniele Ramazzotti
