### ISSUE TITLE
Error installing ASCETIC on MacOS

### ISSUE THREAD

**Issue by AntoniaChroni** [danro9685/ASCETIC#7]
Hey,

I have tried a variety of combinations for Bioconductor/R versions and every time I get the following error (same for 3.17, 3.18). I also tried R 4.2.3, R 4.3.0, and R 4.3.1. Any insights on why the installation is falling? Also, which versions were used to build the ASCETIC R package?

`Warning: package ‘ASCETIC’ is not available for Bioconductor version '3.16'`

**Comment by luca-dex** [comment]
Dear @AntoniaChroni
ASCETIC is not available yet on Bioconductor, we are working to publish it there in coming months. 

In the meanwhile it is possible to install it directly from github.

```
library(devtools)
install_github("danro9685/ASCETIC")
```

**Comment by AntoniaChroni** [comment]
Thank you, that worked. In the vignette, installation via Bioconductor is recommended, fyi. Also, package 'ASCETIC' requires `R >= 4.3.0`.

**Comment by danro9685** [comment]
Great!
We hope to include ASCETIC in the next release of Bioconductor (String 2024).
All the best,
Daniele
