### ISSUE TITLE
Interpretation

### ISSUE THREAD

**Issue by xtmgah** [danro9685/ASCETIC#8]
Dear @luca-dex and @danro9685:

It's a very interesting package. Thanks for developing this. I want to check with you how to use this package and how to interpret the results. For example, for the single sample study as tested dataset. Can you let me know the output information (rankingEstimate, poset and inference). Based on this output, how do I use this information to generate a similar figure as Figure 5b in your manuscript? Also, how do i generated the input similar as amlExample$evolutionary_steps for EvoSigs function? Thanks so much. 

> resExampleSingleSamplesResampling
$dataset
                  CTNNB1 TERT TP53
P-0044337-T01-IM6      0    1    1
P-0013464-T01-IM5      0    1    1
P-0017698-T02-IM6      1    0    0
P-0017415-T01-IM6      0    1    1
P-0017412-T01-IM6      0    1    0
P-0013060-T01-IM5      0    1    1
P-0001307-T01-IM3      1    1    0
P-0038810-T01-IM6      1    1    0
P-0036280-T01-IM6      0    1    1
P-0007157-T01-IM5      1    1    0

$ccfDataset
                     CTNNB1      TERT      TP53
P-0044337-T01-IM6 0.0000000 0.4932976 0.1640625
P-0013464-T01-IM5 0.0000000 0.2231760 0.2167256
P-0017698-T02-IM6 0.7376623 0.0000000 0.0000000
P-0017415-T01-IM6 0.0000000 0.2142857 0.2441506
P-0017412-T01-IM6 0.0000000 0.4850498 0.0000000
P-0013060-T01-IM5 0.0000000 0.2944785 0.3741935
P-0001307-T01-IM3 0.4627249 0.6725664 0.0000000
P-0038810-T01-IM6 0.5017422 0.8268956 0.0000000
P-0036280-T01-IM6 0.0000000 0.4246824 0.5553236
P-0007157-T01-IM5 0.9068323 0.0000000 0.0000000

$rankingEstimate
       variable rank
CTNNB1        1    2
TERT          2    1
TP53          3    0

$poset
  1 2 3
1 0 0 0
2 1 0 0
3 0 1 0

$inference
$inference$aic
  1 2 3
1 0 0 0
2 1 0 0
3 0 0 0

**Comment by danro9685** [comment]
Dear @xtmgah,

Thank you for your interest in our tool.

Let me first explain to you the outputs of the method:
1) rankingEstimate is telling you the estimated ordering in which the mutations accumulate during cancer progression. In particular, the rank column give you the rank with 0 being the genes occurring first and higher number indicating the ordering.
2) poset is the adjacency matrix derived from the ordering, in this case an arc from variable 2 (TERT) toward 1 (CTNNB1) and from 3 (TP53) toward 2 (TERT) is dericed from TP53 having rank = 0 (first event), TERT rank = 1 and CTNNB1 rank = 2.
3) inference is computed performing the likelihood with on your input data given the poset.

An example of the input for XX is in amlExample$survival_data and this is a data.frame of two columns, Times and Status, reporting the Time of survival and the Status (1,0, i.e., Event Yes or No) with rownames being the patients/samples names.

I hope this clarifies your doubles, if you have further questions, please do not esitate to contact us for additional support.

All the best,
Daniele Ramazzotti
