### ISSUE TITLE
cross validation score

### ISSUE THREAD

**Issue by wt12318** [danro9685/ASCETIC#9]
Hi,
Thanks for developing this package. In the paper, it states "... and further discuss here the inferred relations with a cross validation score higher than 0.5". How to get this cross validation score? By running `asceticCCFAssessment`, I can only get ranking, poset, and aic. Thanks.

**Comment by danro9685** [comment]
Dear @wt12318,
Please use the function asceticCCFAssessment to obtain the cross validation score.
It was recently added, so you might need to update your package.
If you need help, please contact me at daniele.ramazzotti@unimib.it
All the best,
Daniele
